
export const crosses = [
    {
        stockCode: "0001.HK",
        stockDescription: "CK Hutchison Holdings",
        currency: "HKD",
        buyOrders: [
            {
                desk: "Block HK",
                trader: "John Doe",
                quantity: 30000,
                stockCode: "0001.HK",
                notionalValue: 1500000,
                instruction: "Limit",
                price: 50,
                client: "CITICS",
                time: "09:30:00"
            },
            {
                desk: "LowTouch TK",
                trader: "Jane Smith",
                quantity: 20000,
                stockCode: "0001.HK",
                notionalValue: 960000,
                instruction: "Market",
                price: 48,
                client: "Client Masked",
                time: "09:35:00"
            },
            {
                desk: "HighTouch SG",
                trader: "Michael Johnson",
                quantity: 10050,
                stockCode: "0001.HK",
                notionalValue: 552750,
                instruction: "Market",
                price: 55,
                client: "Millennium Capital",
                time: "09:40:00"
            },
            {
                desk: "Block HK",
                trader: "Emily Brown",
                quantity: 1200,
                stockCode: "0001.HK",
                notionalValue: 63600,
                instruction: "Limit",
                price: 53,
                client: "Goldman Sachs",
                time: "09:45:00"
            }
        ],
        sellOrders: [
            {
                desk: "Equity Derivatives HK",
                trader: "David Chen",
                stockCode: "0001.HK",
                quantity: 80000,
                notionalValue: 4480000,
                instruction: "Market",
                price: 56,
                client: "JP Morgan",
                time: "09:50:00"
            },
            {
                desk: "HighTouch HK",
                trader: "Sophia Liu",
                stockCode: "0001.HK",
                quantity: 7000,
                notionalValue: 406000,
                instruction: "Limit",
                price: 58,
                client: "Deutsche Bank",
                time: "09:55:00"
            }
        ]
    },
    {
        stockCode: "0388.HK",
        stockDescription: "Hong Kong Exchanges and Clearing",
        currency: "HKD",
        buyOrders: [
            {
                desk: "LowTouch",
                trader: "Jessica Wong",
                stockCode: "0388.HK",
                quantity: 150,
                notionalValue: 45000,
                instruction: "Limit",
                price: 295,
                client: "Client Masked",
                time: "10:05:00"
            }
        ],
        sellOrders: [
            {
                desk: "Facilitation HK",
                trader: "David Chen",
                stockCode: "0388.HK",
                quantity: 80,
                notionalValue: 24800,
                instruction: "Market",
                price: 310,
                client: "Client Masked",
                time: "10:10:00"
            },
            {
                desk: "HighTouch India",
                trader: "Sophia Liu",
                stockCode: "0388.HK",
                quantity: 70,
                notionalValue: 21350,
                instruction: "Limit",
                price: 305,
                client: "Deutsche Bank",
                time: "10:15:00"
            }
        ]
    },
    {
        stockCode: "0700.HK",
        stockDescription: "Tencent Holdings",
        currency: "HKD",
        buyOrders: [
            {
                desk: "Block",
                trader: "James Wang",
                stockCode: "0700.HK",
                quantity: 250,
                notionalValue: 60000,
                instruction: "Limit",
                price: 240,
                client: "Schroders",
                time: "10:30:00"
            },
            {
                desk: "LowTouch",
                trader: "Michelle Chen",
                stockCode: "0700.HK",
                quantity: 180,
                notionalValue: 42840,
                instruction: "Market",
                price: 238,
                client: "Client Masked",
                time: "10:35:00"
            }
        ],
        sellOrders: [
            {
                desk: "HighTouch TK",
                trader: "Daniel Liu",
                stockCode: "0700.HK",
                quantity: 140,
                notionalValue: 34300,
                instruction: "Market",
                price: 245,
                client: "Nomura",
                time: "10:40:00"
            },
            {
                desk: "HighTouch HK",
                trader: "Sophie Wang",
                stockCode: "0700.HK",
                quantity: 120,
                notionalValue: 29040,
                instruction: "Limit",
                price: 242,
                client: "JP Morgan",
                time: "10:45:00"
            }
        ]
    },
    {
        stockCode: "2318.HK",
        stockDescription: "Ping An Insurance Group",
        currency: "HKD",
        buyOrders: [
            {
                desk: "Facilitation HK",
                trader: "Andy Zhang",
                stockCode: "2318.HK",
                quantity: 180,
                notionalValue: 8694,
                instruction: "Limit",
                price: 48.3,
                client: "Client Masked",
                time: "11:00:00"
            },
            {
                desk: "Block",
                trader: "Grace Liu",
                stockCode: "2318.HK",
                quantity: 150,
                notionalValue: 7050,
                instruction: "Market",
                price: 47,
                client: "UBS",
                time: "11:05:00"
            }
        ],
        sellOrders: [
            {
                desk: "HighTouch HK",
                trader: "Brian Chen",
                stockCode: "2318.HK",
                quantity: 200,
                notionalValue: 9700,
                instruction: "Market",
                price: 48.5,
                client: "Client Masked",
                time: "11:10:00"
            }
        ]
    }
];
export const holdings = [
    {
        stockCode: "0001.HK",
        stockDescription: "CK Hutchison Holdings",
        currency: "HKD",
        score:[1, 2, 3, 4, 5],
        client: "JP Morgan",
        market: "HK",
        quantity: 25000,
        notionalValue: 1025000,
        quantityChange: 5000,
        sharesPercent: 2,
        lastDate: "08/06/23"
    },
    {
        stockCode: "0001.HK",
        stockDescription: "CK Hutchison Holdings",
        currency: "HKD",
        score:[1, 2],
        client: "Deutsche Bank",
        market: "HK",
        quantity: 2000,
        notionalValue: 82000,
        quantityChange: 1000,
        sharesPercent: 0.3,
        lastDate: "08/06/23"
    },
    {
        stockCode: "0001.HK",
        stockDescription: "CK Hutchison Holdings",
        currency: "HKD",
        score:[1, 2, 3],
        client: "Schroders",
        market: "HK",
        quantity: 3500,
        notionalValue: 143500,
        quantityChange: 500,
        sharesPercent: 1.4,
        lastDate: "09/06/23"
    },
    {
        stockCode: "0001.HK",
        stockDescription: "CK Hutchison Holdings",
        currency: "HKD",
        score:[1, 2, 3, 4],
        client: "Morgan Stanley",
        market: "HK",
        quantity: 1450,
        notionalValue: 594500,
        quantityChange: 1200,
        sharesPercent: 1.01,
        lastDate: "09/06/23"
    },
    {
        stockCode: "0005.HK",
        stockDescription: "HSBC Holdings",
        currency: "HKD",
        score:[1, 2, 3, 4, 5, 6, 7, 8],
        client: "Millennium Capital",
        market: "HK",
        quantity: 2500,
        notionalValue: 1025000,
        quantityChange: 6000,
        sharesPercent: 2,
        lastDate: "08/06/23"
    },
    {
        stockCode: "0005.HK",
        stockDescription: "HSBC Holdings",
        currency: "HKD",
        score:[1, 2, 3],
        client: "Schroders",
        market: "HK",
        quantity: 3500,
        notionalValue: 143500,
        quantityChange: 500,
        sharesPercent: 1.4,
        lastDate: "09/06/23"
    },
    {
        stockCode: "0005.HK",
        stockDescription: "HSBC Holdings",
        currency: "HKD",
        score:[1, 2, 3, 4],
        client: "Morgan Stanley",
        market: "HK",
        quantity: 14500,
        notionalValue: 5945000,
        quantityChange: 1200,
        sharesPercent: 1.01,
        lastDate: "09/06/23"
    }
];
export const tradeHistory = [
    {
        stockCode: '0001.HK',
        stockDescription: 'CK Hutchison Holdings',
        currency: 'HKD',
        side: 'Buy',
        client: 'Goldman Sachs',
        Market: 'HK',
        date: '08/06/23',
        averagePrice: 50.25,
        desk: 'LowTouch HK',
        trader: 'John Doe',
        originalQuantity: 30000,
        originalNotionalValue: 1500000,
        currentQuantity: 25000,
        currentNotionalValue: 1250000,
    },
    {
        stockCode: '0001.HK',
        stockDescription: 'CK Hutchison Holdings',
        currency: 'HKD',
        side: 'Buy',
        client: 'Goldman Sachs',
        Market: 'HK',
        date: '08/06/23',
        averagePrice: 48.75,
        desk: 'HighTouch SG',
        trader: 'Jane Smith',
        originalQuantity: 20000,
        originalNotionalValue: 960000,
        currentQuantity: 18000,
        currentNotionalValue: 864000,
    },
    {
        stockCode: '0700.HK',
        stockDescription: 'Tencent Holdings',
        currency: 'HKD',
        side: 'Buy',
        client: 'Goldman Sachs',
        Market: 'HK',
        date: '08/06/23',
        averagePrice: 535.50,
        desk: 'LowTouch HK',
        trader: 'Emily Brown',
        originalQuantity: 1200,
        originalNotionalValue: 63600,
        currentQuantity: 1000,
        currentNotionalValue: 53550,
    },
    {
        stockCode: '0001.HK',
        stockDescription: 'CK Hutchison Holdings',
        currency: 'HKD',
        side: 'Sell',
        client: 'Goldman Sachs',
        Market: 'HK',
        date: '08/06/23',
        averagePrice: 56.50,
        desk: 'Equity Derivatives HK',
        trader: 'David Chen',
        originalQuantity: 80000,
        originalNotionalValue: 4480000,
        currentQuantity: 78000,
        currentNotionalValue: 4368000,
    },
    {
        stockCode: '0001.HK',
        stockDescription: 'CK Hutchison Holdings',
        currency: 'HKD',
        side: 'Sell',
        client: 'Goldman Sachs',
        Market: 'HK',
        date: '09/06/23',
        averagePrice: 58.20,
        desk: 'HighTouch HK',
        trader: 'Sophia Liu',
        originalQuantity: 7000,
        originalNotionalValue: 406000,
        currentQuantity: 6500,
        currentNotionalValue: 377750,
    },
    {
        stockCode: '0001.HK',
        stockDescription: 'CK Hutchison Holdings',
        currency: 'HKD',
        side: 'Sell',
        client: 'Goldman Sachs',
        Market: 'HK',
        date: '05/06/23',
        averagePrice: 53.80,
        desk: 'LowTouch AU',
        trader: 'John Smith',
        originalQuantity: 15000,
        originalNotionalValue: 807000,
        currentQuantity: 14500,
        currentNotionalValue: 780500,
    },
    {
        stockCode: '0700.HK',
        stockDescription: 'Tencent Holdings',
        currency: 'HKD',
        side: 'Sell',
        client: 'Goldman Sachs',
        Market: 'HK',
        date: '08/06/23',
        averagePrice: 556.80,
        desk: 'Equity Derivatives SG',
        trader: 'Michael Johnson',
        originalQuantity: 5000,
        originalNotionalValue: 276250,
        currentQuantity: 4800,
        currentNotionalValue: 265200,
    },
    {
        stockCode: '0005.HK',
        stockDescription: 'HSBC Holdings',
        currency: 'HKD',
        side: 'Buy',
        Market: 'HK',
        client: 'Deutsche Bank',
        date: '08/06/23',
        averagePrice: 50.25,
        desk: 'LowTouch HK',
        trader: 'John Doe',
        originalQuantity: 30000,
        originalNotionalValue: 1500000,
        currentQuantity: 25000,
        currentNotionalValue: 1250000,
    },
    {
        stockCode: '0005.HK',
        stockDescription: 'HSBC Holdings',
        currency: 'HKD',
        side: 'Buy',
        Market: 'HK',
        client: 'Morgan Stanley',
        date: '09/06/23',
        averagePrice: 48.75,
        desk: 'HighTouch SG',
        trader: 'Jane Smith',
        originalQuantity: 20000,
        originalNotionalValue: 960000,
        currentQuantity: 18000,
        currentNotionalValue: 864000,
    },
    {
        stockCode: '0005.HK',
        stockDescription: 'HSBC Holdings',
        currency: 'HKD',
        side: 'Sell',
        Market: 'HK',
        client: 'Millennium Capital',
        date: '08/06/23',
        averagePrice: 56.50,
        desk: 'Equity Derivatives HK',
        trader: 'David Chen',
        originalQuantity: 80000,
        originalNotionalValue: 4480000,
        currentQuantity: 78000,
        currentNotionalValue: 4368000,
    }
];
export const tasks = [
    {
        id: 1,
        type: "Potential Cross",
        stockCode: "0001.HK",
        stockDescription: "CK Hutchison Holdings",
        status: "pending",
        timestamp: "2021-06-23T10:00:00.000Z",
        isLive: true,
        market: "HK",
        metadata: "Contact HK low-touch",
        ranking: 8,
        desk: "Low-touch HK",
        quantity: 10000,
        trader: "Horatio",
        side: "Buy"
    },
    {
        id: 2,
        type: "Desk Cross",
        stockCode: "0005.HK",
        stockDescription: "HSBC Holdings",
        status: "pending",
        timestamp: "2021-06-23T11:00:00.000Z",
        isLive: true,
        market: "HK",
        metadata: "Contact Lee McQueen",
        ranking: 9,
        desk: "Block desk HK",
        client: "JP Morgan",
        quantity: 45000,
        trader: "Harper",
        side: "Sell",
        orderId: 1125111
    },
    {
        id: 3,
        type: "Blast",
        stockCode: "0003.HK",
        stockDescription: "Hong Kong and China Gas",
        status: "completed",
        timestamp: "2021-06-23T11:30:00.000Z",
        isLive: true,
        market: "HK",
        metadata: "Contact JP Morgan Block desk",
        ranking: 5
    },
    {
        id: 4,
        type: "Blast",
        stockCode: "0005.HK",
        stockDescription: "Hong Kong and China Gas",
        status: "pending",
        timestamp: "2021-06-23T11:35:00.000Z",
        isLive: false,
        market: "HK",
        metadata: "Goldman Facil desk",
        ranking: 3
    },
    {
        id: 5,
        type: "Order",
        stockCode: "8602.T",
        stockDescription: "Daiwa Securities",
        status: "pending",
        timestamp: "2021-06-23T11:36:00.000Z",
        isLive: true,
        market: "TK",
        metadata: "Deutsche aggressive seller",
        ranking: 6,
        desk: "Facil desk Tokyo",
        client: "Deutsche Bank",
        quantity: 900000,
        trader: "Harry",
        side: "Sell",
        orderId: 1225117
    },
    {
        id: 6,
        type: "Order",
        stockCode: "8604.T",
        stockDescription: "Nomura Holdings",
        status: "pending",
        timestamp: "2021-06-23T11:36:00.000Z",
        isLive: true,
        market: "TK",
        metadata: "Morgan Stanley passive buyer",
        ranking: 2,
        client: "Morgan Stanley",
        quantity: 22400,
        side: "Buy",
        orderId: 1235668
    },
    {
        id: 6,
        type: "Alert",
        stockCode: "8604.T",
        stockDescription: "Nomura Holdings",
        status: "pending",
        timestamp: "2021-06-23T11:36:00.000Z",
        isLive: true,
        market: "TK",
        metadata: "VWAP algo paused",
        ranking: 1,
        client: "JP Morgan",
        quantity: 45000,
        side: "Sell",
        orderId: 1234567

    },
    {
        id: 7,
        type: "IOI Cross",
        stockCode: "2800.HK",
        stockDescription: "Tracker Fund of Hong Kong",
        status: "pending",
        timestamp: "2021-06-23T11:36:20.000Z",
        isLive: true,
        market: "HK",
        metadata: "Large IOI from Goldman",
        ranking: 6,
        client: "Goldman Sachs",
        quantity: 1900000,
        side: "Buy",
        trader: "Sophia Liu",
    }
];
export const baskets = [
    {
        name: 'Hong Kong Portfolio',
        basketId: 1,
        numberOfConstituents: 8,
        client: 'JP Morgan',
        orderNotionalValue: 0,
        executedNotionalValue: 0,
        constituents:  [{
            "executionAlgo": "Price Inline",
            "ivwap": 40.24,
            "performanceVsIVWAPBPS": 9,
            "performanceVsIVWAP": 9000,
            "performanceVsArrivalBPS": 8,
            "performanceVsArrival": 8850,
            "arrivalPrice": 41,
            "residualNotionalValue": 0,
            "orderNotionalValue": 42360000,
            "executedNotionalValue": 43207200,
            "pending": 0,
            "executed": 1059000,
            "adv20": 0.35,
            "volatility": 19.6,
            "averagePrice": 40.80,
            "blg": "1 HK",
            "arrivalTime": "08:45:23",
            "side": "Sell",
            "price": 40,
            "quantity": 1059000,
            "orderId": 1,
            "clientOrderId": 46,
            "instruction": "LOB",
            "client": "JP Morgan",
            "orderState": "FILLED",
            "stockCode": "0001.HK",
            "stockDescription": "CK Hutchison Holdings"
        },
            {
                "executionAlgo": "VWAP",
                "ivwap": 60.55,
                "performanceVsIVWAPBPS": 5.7,
                "performanceVsIVWAP": 3500,
                "performanceVsArrivalBPS": 14.7,
                "performanceVsArrival": -9000,
                "arrivalPrice": 60,
                "residualNotionalValue": 0,
                "orderNotionalValue": 60400000,
                "executedNotionalValue": 60400000,
                "pending": 0,
                "executed": 10000,
                "adv20": 0.15,
                "volatility": 17.6,
                "averagePrice": 60.90,
                "blg": "5 HK",
                "arrivalTime": "08:47:00",
                "side": "Buy",
                "price": 60.40,
                "quantity": 1000000,
                "orderId": 2,
                "clientOrderId": 4231,
                "instruction": "LOB",
                "client": "Schroders",
                "orderState": "ACKED",
                "stockCode": "0005.HK",
                "stockDescription": "HSBC Holdings"
            },
            {
                "executionAlgo": "TWAP",
                "ivwap": 59.55,
                "performanceVsIVWAPBPS": 0,
                "performanceVsIVWAP": 0,
                "performanceVsArrivalBPS": 0,
                "performanceVsArrival": 0,
                "arrivalPrice": 58,
                "residualNotionalValue": 290000,
                "orderNotionalValue": 290000,
                "executedNotionalValue": 0,
                "pending": 5000,
                "executed": 0,
                "adv20": 0.25,
                "volatility": 11.6,
                "averagePrice": 0,
                "blg": "2 HK",
                "arrivalTime": "08:48:00",
                "side": "Sell",
                "price": 58,
                "quantity": 5000,
                "orderId": 3,
                "clientOrderId": 42,
                "instruction": "MOO",
                "client": "Deutsche Bank",
                "orderState": "NEW ORDER",
                "stockCode": "0002.HK",
                "stockDescription": "CLP Holdings"
            },
            {
                "executionAlgo": "Price Inline",
                "ivwap": 22.45,
                "performanceVsIVWAPBPS": 4.5,
                "performanceVsIVWAP": 2250,
                "performanceVsArrivalBPS": 2.25,
                "performanceVsArrival": 1125,
                "arrivalPrice": 22.2,
                "residualNotionalValue": 0,
                "orderNotionalValue": 44400000,
                "executedNotionalValue": 44872500,
                "pending": 0,
                "executed": 20000,
                "adv20": 0.12,
                "volatility": 29.6,
                "averagePrice": 22.43625,
                "blg": "12 HK",
                "arrivalTime": "08:50:00",
                "side": "Sell",
                "price": 22.1,
                "quantity": 2000000,
                "orderId": 13,
                "clientOrderId": 212,
                "instruction": "LOB",
                "client": "Credit Suisse",
                "orderState": "FILLED",
                "stockCode": "0012.HK",
                "stockDescription": "Henderson Land Development"
            },
            {
                "executionAlgo": "VWAP",
                "ivwap": 18.75,
                "performanceVsIVWAPBPS": 3.75,
                "performanceVsIVWAP": 1875,
                "performanceVsArrivalBPS": 1.875,
                "performanceVsArrival": 937.5,
                "arrivalPrice": 18.5,
                "residualNotionalValue": 3700,
                "orderNotionalValue": 37000,
                "executedNotionalValue": 33300,
                "pending": 200,
                "executed": 1800,
                "adv20": 0.10,
                "volatility": 9.6,
                "averagePrice": 18.5,
                "blg": "11 HK",
                "arrivalTime": "08:55:00",
                "side": "Buy",
                "price": 18.5,
                "quantity": 2000,
                "orderId": 14,
                "clientOrderId": 213,
                "instruction": "MOO",
                "client": "Barclays",
                "orderState": "PARTIAL FILL",
                "stockCode": "0011.HK",
                "stockDescription": "Hang Seng Bank"
            },
            {
                "executionAlgo": "Price Inline",
                "ivwap": 33.3,
                "performanceVsIVWAPBPS": 1.65,
                "performanceVsIVWAP": 825,
                "performanceVsArrivalBPS": 0.825,
                "performanceVsArrival": 412.5,
                "arrivalPrice": 33,
                "residualNotionalValue": 0,
                "orderNotionalValue": 9900000,
                "executedNotionalValue": 9967500,
                "pending": 0,
                "executed": 3000,
                "adv20": 0.15,
                "volatility": 15.3,
                "averagePrice": 33.225,
                "blg": "16 HK",
                "arrivalTime": "09:00:00",
                "side": "Sell",
                "price": 33,
                "quantity": 300000,
                "orderId": 15,
                "clientOrderId": 214,
                "instruction": "LOB",
                "client": "UBS",
                "orderState": "ACKED",
                "stockCode": "0016.HK",
                "stockDescription": "Sun Hung Kai Properties"
            },
            {
                "executionAlgo": "TWAP",
                "ivwap": 28.5,
                "performanceVsIVWAPBPS": 1.425,
                "performanceVsIVWAP": 712.5,
                "performanceVsArrivalBPS": 0.7125,
                "performanceVsArrival": 356.25,
                "arrivalPrice": 28.25,
                "residualNotionalValue": 0,
                "orderNotionalValue": 84750,
                "executedNotionalValue": 85312.5,
                "pending": 0,
                "executed": 3000,
                "adv20": 0.2,
                "volatility": 10,
                "averagePrice": 28.4375,
                "blg": "17 HK",
                "arrivalTime": "09:05:00",
                "side": "Buy",
                "price": 28.25,
                "quantity": 3000,
                "orderId": 16,
                "clientOrderId": 215,
                "instruction": "MOO",
                "client": "Bank of America Merrill Lynch",
                "orderState": "NEW ORDER",
                "stockCode": "0017.HK",
                "stockDescription": "New World Development"
            },
            {
                "executionAlgo": "VWAP",
                "ivwap": 25.2,
                "performanceVsIVWAPBPS": 1.26,
                "performanceVsIVWAP": 630,
                "performanceVsArrivalBPS": 0.63,
                "performanceVsArrival": 315,
                "arrivalPrice": 25,
                "residualNotionalValue": 5040,
                "orderNotionalValue": 504000,
                "executedNotionalValue": 453600,
                "pending": 200,
                "executed": 1800,
                "adv20": 0.085,
                "volatility": 21.2,
                "averagePrice": 25.2,
                "blg": "19 HK",
                "arrivalTime": "09:10:00",
                "side": "Sell",
                "price": 25,
                "quantity": 20000,
                "orderId": 17,
                "clientOrderId": 216,
                "instruction": "LOB",
                "client": "Nomura",
                "orderState": "PARTIAL FILL",
                "stockCode": "0019.HK",
                "stockDescription": "Swire Pacific"
            }
        ]
    },
    {
        name: 'Tokyo Portfolio',
        basketId: 2,
        client: "Schroders",
        numberOfConstituents: 10,
        orderNotionalValue: 0,
        executedNotionalValue: 0,
        constituents: [{
            "executionAlgo": "VWAP",
            "ivwap": 1500,
            "performanceVsIVWAPBPS": 2,
            "performanceVsIVWAP": 3000,
            "performanceVsArrivalBPS": 1,
            "performanceVsArrival": 1500,
            "arrivalPrice": 1495,
            "residualNotionalValue": 0,
            "orderNotionalValue": 300000000,
            "executedNotionalValue": 297000000,
            "pending": 0,
            "executed": 2000,
            "adv20": 0.003,
            "volatility": 13.6,
            "averagePrice": 1501,
            "blg": "6501 TYO",
            "arrivalTime": "09:30:00",
            "side": "Buy",
            "price": 1500,
            "quantity": 200000,
            "orderId": 4,
            "clientOrderId": 100,
            "instruction": "LOB",
            "client": "UBS",
            "orderState": "FILLED",
            "stockCode": "6501.T",
            "stockDescription": "Hitachi"
        },
            {
                "executionAlgo": "TWAP",
                "ivwap": 6500,
                "performanceVsIVWAPBPS": -1,
                "performanceVsIVWAP": -6500,
                "performanceVsArrivalBPS": -0.5,
                "performanceVsArrival": -3250,
                "arrivalPrice": 6505,
                "residualNotionalValue": 0,
                "orderNotionalValue": 6500000,
                "executedNotionalValue": 6473750,
                "pending": 0,
                "executed": 1000,
                "adv20": 0.001,
                "volatility": 23.5,
                "averagePrice": 6492.5,
                "blg": "7203 TYO",
                "arrivalTime": "09:35:00",
                "side": "Sell",
                "price": 6500,
                "quantity": 1000,
                "orderId": 5,
                "clientOrderId": 101,
                "instruction": "MOO",
                "client": "Goldman Sachs",
                "orderState": "FILLED",
                "stockCode": "7203.T",
                "stockDescription": "Toyota Motor"
            },
            {
                "executionAlgo": "VWAP",
                "ivwap": 2500,
                "performanceVsIVWAPBPS": 1,
                "performanceVsIVWAP": 3750,
                "performanceVsArrivalBPS": 0.5,
                "performanceVsArrival": 1875,
                "arrivalPrice": 2495,
                "residualNotionalValue": 0,
                "orderNotionalValue": 750000000,
                "executedNotionalValue": 749812500,
                "pending": 0,
                "executed": 3000,
                "adv20": 0.002,
                "volatility": 16,
                "averagePrice": 2499.375,
                "blg": "6758 TYO",
                "arrivalTime": "09:40:00",
                "side": "Buy",
                "price": 2500,
                "quantity": 300000,
                "orderId": 6,
                "clientOrderId": 102,
                "instruction": "LOB",
                "client": "Morgan Stanley",
                "orderState": "FILLED",
                "stockCode": "6758.T",
                "stockDescription": "Sony Group Corporation"
            },
            {
                "executionAlgo": "TWAP",
                "ivwap": 3500,
                "performanceVsIVWAPBPS": -1.5,
                "performanceVsIVWAP": -10500,
                "performanceVsArrivalBPS": -0.75,
                "performanceVsArrival": -5250,
                "arrivalPrice": 3503.75,
                "residualNotionalValue": 17500,
                "orderNotionalValue": 14000000,
                "executedNotionalValue": 13982500,
                "pending": 5,
                "executed": 3995,
                "adv20": 0.0025,
                "volatility": 19,
                "averagePrice": 3499.25,
                "blg": "9984 TYO",
                "arrivalTime": "09:45:00",
                "side": "Sell",
                "price": 3500,
                "quantity": 4000,
                "orderId": 7,
                "clientOrderId": 103,
                "instruction": "MOO",
                "client": "J.P. Morgan",
                "orderState": "PARTIAL FILL",
                "stockCode": "9984.T",
                "stockDescription": "SoftBank Group"
            },
            {
                "executionAlgo": "Price Inline",
                "ivwap": 3200,
                "performanceVsIVWAPBPS": 2,
                "performanceVsIVWAP": 38400,
                "performanceVsArrivalBPS": 1,
                "performanceVsArrival": 19200,
                "arrivalPrice": 3195,
                "residualNotionalValue": 0,
                "orderNotionalValue": 19200000,
                "executedNotionalValue": 19238400,
                "pending": 0,
                "executed": 6000,
                "adv20": 0.001,
                "volatility": 14.1,
                "averagePrice": 3206.4,
                "blg": "7974 TYO",
                "arrivalTime": "09:50:00",
                "side": "Buy",
                "price": 3200,
                "quantity": 6000,
                "orderId": 8,
                "clientOrderId": 104,
                "instruction": "LOB",
                "client": "Barclays",
                "orderState": "NEW ORDER",
                "stockCode": "7974.T",
                "stockDescription": "Nintendo Co., Ltd."
            },
            {
                "executionAlgo": "VWAP",
                "ivwap": 900,
                "performanceVsIVWAPBPS": -0.5,
                "performanceVsIVWAP": -4500,
                "performanceVsArrivalBPS": -0.25,
                "performanceVsArrival": -2250,
                "arrivalPrice": 900.25,
                "residualNotionalValue": 9000,
                "orderNotionalValue": 9009000,
                "executedNotionalValue": 9000000,
                "pending": 10,
                "executed": 10000,
                "adv20": 0.003,
                "volatility": 9.6,
                "averagePrice": 899.75,
                "blg": "7267 TYO",
                "arrivalTime": "09:55:00",
                "side": "Sell",
                "price": 900,
                "quantity": 10010,
                "orderId": 9,
                "clientOrderId": 105,
                "instruction": "MOO",
                "client": "Credit Suisse",
                "orderState": "PARTIAL FILL",
                "stockCode": "7267.T",
                "stockDescription": "Honda Motor Co., Ltd."
            },
            {
                "executionAlgo": "TWAP",
                "ivwap": 4000,
                "performanceVsIVWAPBPS": 1.5,
                "performanceVsIVWAP": 18000,
                "performanceVsArrivalBPS": 0.75,
                "performanceVsArrival": 9000,
                "arrivalPrice": 3992.5,
                "residualNotionalValue": 0,
                "orderNotionalValue": 12000000,
                "executedNotionalValue": 12018000,
                "pending": 0,
                "executed": 3000,
                "adv20": 0.002,
                "volatility": 16,
                "averagePrice": 4006,
                "blg": "9433 TYO",
                "arrivalTime": "10:00:00",
                "side": "Buy",
                "price": 4000,
                "quantity": 3000,
                "orderId": 10,
                "clientOrderId": 106,
                "instruction": "LOB",
                "client": "Deutsche Bank",
                "orderState": "FILLED",
                "stockCode": "9433.T",
                "stockDescription": "KDDI Corporation"
            },
            {
                "executionAlgo": "Price Inline",
                "ivwap": 1200,
                "performanceVsIVWAPBPS": -1,
                "performanceVsIVWAP": -14400,
                "performanceVsArrivalBPS": -0.5,
                "performanceVsArrival": -7200,
                "arrivalPrice": 1200.5,
                "residualNotionalValue": 7200,
                "orderNotionalValue": 14414400,
                "executedNotionalValue": 14342400,
                "pending": 6,
                "executed": 11994,
                "adv20": 0.004,
                "volatility": 6,
                "averagePrice": 1198.8,
                "blg": "8035 TYO",
                "arrivalTime": "10:05:00",
                "side": "Sell",
                "price": 1200,
                "quantity": 12000,
                "orderId": 11,
                "clientOrderId": 107,
                "instruction": "MOO",
                "client": "BNP Paribas",
                "orderState": "ACKED",
                "stockCode": "8035.T",
                "stockDescription": "Tokyo Electron"
            },
            {
                "executionAlgo": "VWAP",
                "ivwap": 2800,
                "performanceVsIVWAPBPS": 0.5,
                "performanceVsIVWAP": 2800,
                "performanceVsArrivalBPS": 0.25,
                "performanceVsArrival": 1400,
                "arrivalPrice": 2799.5,
                "residualNotionalValue": 0,
                "orderNotionalValue": 56000000,
                "executedNotionalValue": 56014000,
                "pending": 0,
                "executed": 20000,
                "adv20": 0.001,
                "volatility": 11.6,
                "averagePrice": 2800.7,
                "blg": "6367 TYO",
                "arrivalTime": "10:10:00",
                "side": "Buy",
                "price": 2800,
                "quantity": 20000,
                "orderId": 12,
                "clientOrderId": 108,
                "instruction": "LOB",
                "client": "HSBC",
                "orderState": "FILLED",
                "stockCode": "6367.T",
                "stockDescription": "Daikin Industries, Ltd."
            },
            {
                "executionAlgo": "TWAP",
                "ivwap": 2200,
                "performanceVsIVWAPBPS": -2,
                "performanceVsIVWAP": -176000,
                "performanceVsArrivalBPS": -1,
                "performanceVsArrival": -88000,
                "arrivalPrice": 2201,
                "residualNotionalValue": 176000,
                "orderNotionalValue": 88088000,
                "executedNotionalValue": 87910400,
                "pending": 80,
                "executed": 39840,
                "adv20": 0.0005,
                "volatility": 11,
                "averagePrice": 2201.8,
                "blg": "4543 TYO",
                "arrivalTime": "10:15:00",
                "side": "Sell",
                "price": 2200,
                "quantity": 39920,
                "orderId": 13,
                "clientOrderId": 109,
                "instruction": "MOO",
                "client": "Citigroup",
                "orderState": "PARTIAL FILL",
                "stockCode": "4543.T",
                "stockDescription": "Terumo Corporation"
            }
        ]
    },
    {
        name: 'Singapore Portfolio',
        basketId: 3,
        client: "Deutsche Bank",
        numberOfConstituents: 12,
        orderNotionalValue: 0,
        executedNotionalValue: 0,
        constituents: [
            {
                "executionAlgo": "Price Inline",
                "ivwap": 15,
                "performanceVsIVWAPBPS": 1.5,
                "performanceVsIVWAP": 202.5,
                "performanceVsArrivalBPS": 0.75,
                "performanceVsArrival": 101.25,
                "arrivalPrice": 15.01,
                "residualNotionalValue": 15010,
                "orderNotionalValue": 300200,
                "executedNotionalValue": 285190,
                "pending": 1000,
                "executed": 19000,
                "adv20": 0.004,
                "volatility": 9,
                "averagePrice": 15.01,
                "blg": "D05 SGX",
                "arrivalTime": "10:00:00",
                "side": "Buy",
                "price": 15,
                "quantity": 20000,
                "orderId": 1,
                "clientOrderId": 200,
                "instruction": "LOB",
                "client": "Morgan Stanley",
                "orderState": "ACKED",
                "stockCode": "D05.SI",
                "stockDescription": "DBS Group"
            },
            {
                "executionAlgo": "VWAP",
                "ivwap": 25,
                "performanceVsIVWAPBPS": -0.5,
                "performanceVsIVWAP": -187.5,
                "performanceVsArrivalBPS": -0.25,
                "performanceVsArrival": -93.75,
                "arrivalPrice": 25.01,
                "residualNotionalValue": 0,
                "orderNotionalValue": 750750,
                "executedNotionalValue": 750562.5,
                "pending": 0,
                "executed": 30000,
                "adv20": 0.002,
                "volatility": 10.1,
                "averagePrice": 25.01875,
                "blg": "U11 SGX",
                "arrivalTime": "10:05:00",
                "side": "Sell",
                "price": 25,
                "quantity": 30000,
                "orderId": 2,
                "clientOrderId": 201,
                "instruction": "MOO",
                "client": "Citi",
                "orderState": "FILLED",
                "stockCode": "U11.SI",
                "stockDescription": "United Overseas Bank"
            },
            {
                "executionAlgo": "TWAP",
                "ivwap": 3,
                "performanceVsIVWAPBPS": 2,
                "performanceVsIVWAP": 54,
                "performanceVsArrivalBPS": 1,
                "performanceVsArrival": 27,
                "arrivalPrice": 2.99,
                "residualNotionalValue": 0,
                "orderNotionalValue": 80910,
                "executedNotionalValue": 80964,
                "pending": 0,
                "executed": 27000,
                "adv20": 0.005,
                "volatility": 29.3,
                "averagePrice": 2.997,
                "blg": "C31 SGX",
                "arrivalTime": "10:10:00",
                "side": "Buy",
                "price": 3,
                "quantity": 27000,
                "orderId": 3,
                "clientOrderId": 202,
                "instruction": "LOB",
                "client": "Credit Suisse",
                "orderState": "FILLED",
                "stockCode": "C31.SI",
                "stockDescription": "CapitaLand"
            },
            {
                "executionAlgo": "VWAP",
                "ivwap": 7,
                "performanceVsIVWAPBPS": 1,
                "performanceVsIVWAP": 63,
                "performanceVsArrivalBPS": 0.5,
                "performanceVsArrival": 31.5,
                "arrivalPrice": 7.01,
                "residualNotionalValue": 21021,
                "orderNotionalValue": 168168,
                "executedNotionalValue": 147147,
                "pending": 3000,
                "executed": 21000,
                "adv20": 0.001,
                "volatility": 9.6,
                "averagePrice": 7.005,
                "blg": "Z74 SGX",
                "arrivalTime": "10:15:00",
                "side": "Sell",
                "price": 7,
                "quantity": 24000,
                "orderId": 4,
                "clientOrderId": 203,
                "instruction": "MOO",
                "client": "HSBC",
                "orderState": "ACKED",
                "stockCode": "Z74.SI",
                "stockDescription": "Singtel"
            },
            {
                "executionAlgo": "Price Inline",
                "ivwap": 18,
                "performanceVsIVWAPBPS": 1,
                "performanceVsIVWAP": 162,
                "performanceVsArrivalBPS": 0.5,
                "performanceVsArrival": 81,
                "arrivalPrice": 18.01,
                "residualNotionalValue": 0,
                "orderNotionalValue": 360360,
                "executedNotionalValue": 360462,
                "pending": 0,
                "executed": 20000,
                "adv20": 0.003,
                "volatility": 8.7,
                "averagePrice": 18.0231,
                "blg": "O39 SGX",
                "arrivalTime": "10:20:00",
                "side": "Buy",
                "price": 18,
                "quantity": 20000,
                "orderId": 5,
                "clientOrderId": 204,
                "instruction": "LOB",
                "client": "Goldman Sachs",
                "orderState": "NEW ORDER",
                "stockCode": "O39.SI",
                "stockDescription": "OCBC Bank"
            },
            {
                "executionAlgo": "TWAP",
                "ivwap": 12,
                "performanceVsIVWAPBPS": 0.5,
                "performanceVsIVWAP": 40.5,
                "performanceVsArrivalBPS": 0.25,
                "performanceVsArrival": 20.25,
                "arrivalPrice": 12.01,
                "residualNotionalValue": 0,
                "orderNotionalValue": 264264,
                "executedNotionalValue": 264304.5,
                "pending": 0,
                "executed": 22000,
                "adv20": 0.002,
                "volatility": 1.6,
                "averagePrice": 12.0138,
                "blg": "F34 SGX",
                "arrivalTime": "10:25:00",
                "side": "Sell",
                "price": 12,
                "quantity": 22000,
                "orderId": 6,
                "clientOrderId": 205,
                "instruction": "MOO",
                "client": "UBS",
                "orderState": "FILLED",
                "stockCode": "F34.SI",
                "stockDescription": "Wilmar International"
            },
            {
                "executionAlgo": "Price Inline",
                "ivwap": 10,
                "performanceVsIVWAPBPS": 0.5,
                "performanceVsIVWAP": 32.5,
                "performanceVsArrivalBPS": 0.25,
                "performanceVsArrival": 16.25,
                "arrivalPrice": 10.01,
                "residualNotionalValue": 0,
                "orderNotionalValue": 227270,
                "executedNotionalValue": 227302.5,
                "pending": 0,
                "executed": 22700,
                "adv20": 0.002,
                "volatility": 12.9,
                "averagePrice": 10.0135,
                "blg": "C52 SGX",
                "arrivalTime": "10:30:00",
                "side": "Buy",
                "price": 10,
                "quantity": 22700,
                "orderId": 7,
                "clientOrderId": 206,
                "instruction": "LOB",
                "client": "Bank of America Merrill Lynch",
                "orderState": "FILLED",
                "stockCode": "C52.SI",
                "stockDescription": "ComfortDelGro"
            },
            {
                "executionAlgo": "VWAP",
                "ivwap": 9,
                "performanceVsIVWAPBPS": 0.5,
                "performanceVsIVWAP": 34.5,
                "performanceVsArrivalBPS": 0.25,
                "performanceVsArrival": 17.25,
                "arrivalPrice": 9.01,
                "residualNotionalValue": 0,
                "orderNotionalValue": 198198,
                "executedNotionalValue": 198232.5,
                "pending": 0,
                "executed": 22000,
                "adv20": 0.003,
                "volatility": 16,
                "averagePrice": 9.01025,
                "blg": "G13 SGX",
                "arrivalTime": "10:35:00",
                "side": "Sell",
                "price": 9,
                "quantity": 22000,
                "orderId": 8,
                "clientOrderId": 207,
                "instruction": "MOO",
                "client": "Nomura",
                "orderState": "FILLED",
                "stockCode": "G13.SI",
                "stockDescription": "Genting Singapore"
            },
            {
                "executionAlgo": "TWAP",
                "ivwap": 6,
                "performanceVsIVWAPBPS": 0.5,
                "performanceVsIVWAP": 25.5,
                "performanceVsArrivalBPS": 0.25,
                "performanceVsArrival": 12.75,
                "arrivalPrice": 6.01,
                "residualNotionalValue": 12060,
                "orderNotionalValue": 130130,
                "executedNotionalValue": 118070,
                "pending": 2000,
                "executed": 19700,
                "adv20": 0.003,
                "volatility": 19.1,
                "averagePrice": 6.005,
                "blg": "C07 SGX",
                "arrivalTime": "10:40:00",
                "side": "Buy",
                "price": 6,
                "quantity": 21700,
                "orderId": 9,
                "clientOrderId": 208,
                "instruction": "LOB",
                "client": "Deutsche Bank",
                "orderState": "PARTIAL FILL",
                "stockCode": "C07.SI",
                "stockDescription": "Jardine Cycle & Carriage"
            },
            {
                "executionAlgo": "Price Inline",
                "ivwap": 8,
                "performanceVsIVWAPBPS": 0.5,
                "performanceVsIVWAP": 26,
                "performanceVsArrivalBPS": 0.25,
                "performanceVsArrival": 13,
                "arrivalPrice": 8.01,
                "residualNotionalValue": 16032,
                "orderNotionalValue": 160160,
                "executedNotionalValue": 144128,
                "pending": 2000,
                "executed": 18000,
                "adv20": 0.004,
                "volatility": 13.4,
                "averagePrice": 8.007,
                "blg": "H78 SGX",
                "arrivalTime": "10:45:00",
                "side": "Sell",
                "price": 8,
                "quantity": 20000,
                "orderId": 10,
                "clientOrderId": 209,
                "instruction": "MOO",
                "client": "J.P. Morgan",
                "orderState": "NEW ORDER",
                "stockCode": "H78.SI",
                "stockDescription": "Hongkong Land"
            },
            {
                "executionAlgo": "VWAP",
                "ivwap": 13,
                "performanceVsIVWAPBPS": 0.5,
                "performanceVsIVWAP": 44,
                "performanceVsArrivalBPS": 0.25,
                "performanceVsArrival": 22,
                "arrivalPrice": 13.01,
                "residualNotionalValue": 0,
                "orderNotionalValue": 286286,
                "executedNotionalValue": 286330,
                "pending": 0,
                "executed": 22000,
                "adv20": 0.001,
                "volatility": 13.7,
                "averagePrice": 13.015,
                "blg": "C09 SGX",
                "arrivalTime": "10:50:00",
                "side": "Buy",
                "price": 13,
                "quantity": 22000,
                "orderId": 11,
                "clientOrderId": 210,
                "instruction": "LOB",
                "client": "Morgan Stanley",
                "orderState": "FILLED",
                "stockCode": "C09.SI",
                "stockDescription": "City Developments"
            },
            {
                "executionAlgo": "TWAP",
                "ivwap": 11,
                "performanceVsIVWAPBPS": 0.5,
                "performanceVsIVWAP": 33,
                "performanceVsArrivalBPS": 0.25,
                "performanceVsArrival": 16.5,
                "arrivalPrice": 11.01,
                "residualNotionalValue": 0,
                "orderNotionalValue": 242242,
                "executedNotionalValue": 242275.5,
                "pending": 0,
                "executed": 22000,
                "adv20": 0.002,
                "volatility": 12.6,
                "averagePrice": 11.0125,
                "blg": "C38U SGX",
                "arrivalTime": "10:55:00",
                "side": "Sell",
                "price": 11,
                "quantity": 22000,
                "orderId": 12,
                "clientOrderId": 211,
                "instruction": "MOO",
                "client": "Citi",
                "orderState": "FILLED",
                "stockCode": "C38U.SI",
                "stockDescription": "CapitaLand Mall Trust"
            }
        ]

    },
];

