
export const crosses = [
    {
        stockCode: "0001.HK",
        stockDescription: "CK Hutchison Holdings",
        currency: "HKD",
        buyOrders: [
            {
                desk: "Block HK",
                trader: "John Doe",
                quantity: 30000,
                notionalValue: 1500000,
                instruction: "Limit",
                price: 50,
                client: "CITICS",
                time: "09:30:00"
            },
            {
                desk: "LowTouch TK",
                trader: "Jane Smith",
                quantity: 20000,
                notionalValue: 960000,
                instruction: "Market",
                price: 48,
                client: "Client Masked",
                time: "09:35:00"
            },
            {
                desk: "HighTouch SG",
                trader: "Michael Johnson",
                quantity: 10050,
                notionalValue: 552750,
                instruction: "Market",
                price: 55,
                client: "Millennium Capital",
                time: "09:40:00"
            },
            {
                desk: "Block HK",
                trader: "Emily Brown",
                quantity: 1200,
                notionalValue: 63600,
                instruction: "Limit",
                price: 53,
                client: "Goldman Sachs",
                time: "09:45:00"
            }
        ],
        sellOrders: [
            {
                desk: "Equity Derivatives HK",
                trader: "David Chen",
                quantity: 80000,
                notionalValue: 4480000,
                instruction: "Market",
                price: 56,
                client: "JP Morgan",
                time: "09:50:00"
            },
            {
                desk: "HighTouch HK",
                trader: "Sophia Liu",
                quantity: 7000,
                notionalValue: 406000,
                instruction: "Limit",
                price: 58,
                client: "Deutsche Bank",
                time: "09:55:00"
            }
        ]
    },
    {
        stockCode: "0388.HK",
        stockDescription: "Hong Kong Exchanges and Clearing",
        currency: "HKD",
        buyOrders: [
            {
                desk: "LowTouch",
                trader: "Jessica Wong",
                quantity: 150,
                notionalValue: 45000,
                instruction: "Limit",
                price: 295,
                client: "Client Masked",
                time: "10:05:00"
            }
        ],
        sellOrders: [
            {
                desk: "Facilitation HK",
                trader: "David Chen",
                quantity: 80,
                notionalValue: 24800,
                instruction: "Market",
                price: 310,
                client: "Client Masked",
                time: "10:10:00"
            },
            {
                desk: "HighTouch India",
                trader: "Sophia Liu",
                quantity: 70,
                notionalValue: 21350,
                instruction: "Limit",
                price: 305,
                client: "Deutsche Bank",
                time: "10:15:00"
            }
        ]
    },
    {
        stockCode: "0700.HK",
        stockDescription: "Tencent Holdings",
        currency: "HKD",
        buyOrders: [
            {
                desk: "Block",
                trader: "James Wang",
                quantity: 250,
                notionalValue: 60000,
                instruction: "Limit",
                price: 240,
                client: "Schroders",
                time: "10:30:00"
            },
            {
                desk: "LowTouch",
                trader: "Michelle Chen",
                quantity: 180,
                notionalValue: 42840,
                instruction: "Market",
                price: 238,
                client: "Client Masked",
                time: "10:35:00"
            }
        ],
        sellOrders: [
            {
                desk: "HighTouch TK",
                trader: "Daniel Liu",
                quantity: 140,
                notionalValue: 34300,
                instruction: "Market",
                price: 245,
                client: "Nomura",
                time: "10:40:00"
            },
            {
                desk: "HighTouch HK",
                trader: "Sophie Wang",
                quantity: 120,
                notionalValue: 29040,
                instruction: "Limit",
                price: 242,
                client: "JP Morgan",
                time: "10:45:00"
            }
        ]
    },
    {
        stockCode: "2318.HK",
        stockDescription: "Ping An Insurance Group",
        currency: "HKD",
        buyOrders: [
            {
                desk: "Facilitation HK",
                trader: "Andy Zhang",
                quantity: 180,
                notionalValue: 8694,
                instruction: "Limit",
                price: 48.3,
                client: "Client Masked",
                time: "11:00:00"
            },
            {
                desk: "Block",
                trader: "Grace Liu",
                quantity: 150,
                notionalValue: 7050,
                instruction: "Market",
                price: 47,
                client: "UBS",
                time: "11:05:00"
            }
        ],
        sellOrders: [
            {
                desk: "HighTouch HK",
                trader: "Brian Chen",
                quantity: 200,
                notionalValue: 9700,
                instruction: "Market",
                price: 48.5,
                client: "Client Masked",
                time: "11:10:00"
            }
        ]
    }
];
export const holdings = [
    {
        stockCode: "0001.HK",
        stockDescription: "CK Hutchison Holdings",
        currency: "HKD",
        score:[1, 2, 3, 4, 5],
        client: "JP Morgan",
        market: "HK",
        quantity: 25000,
        notionalValue: 1025000,
        quantityChange: 5000,
        sharesPercent: 2,
        lastDate: "08/06/23"
    },
    {
        stockCode: "0001.HK",
        stockDescription: "CK Hutchison Holdings",
        currency: "HKD",
        score:[1, 2],
        client: "Deutsche Bank",
        market: "HK",
        quantity: 2000,
        notionalValue: 82000,
        quantityChange: 1000,
        sharesPercent: 0.3,
        lastDate: "08/06/23"
    },
    {
        stockCode: "0001.HK",
        stockDescription: "CK Hutchison Holdings",
        currency: "HKD",
        score:[1, 2, 3],
        client: "Schroders",
        market: "HK",
        quantity: 3500,
        notionalValue: 143500,
        quantityChange: 500,
        sharesPercent: 1.4,
        lastDate: "09/06/23"
    },
    {
        stockCode: "0001.HK",
        stockDescription: "CK Hutchison Holdings",
        currency: "HKD",
        score:[1, 2, 3, 4],
        client: "Morgan Stanley",
        market: "HK",
        quantity: 1450,
        notionalValue: 594500,
        quantityChange: 1200,
        sharesPercent: 1.01,
        lastDate: "09/06/23"
    },
    {
        stockCode: "0005.HK",
        stockDescription: "HSBC Holdings",
        currency: "HKD",
        score:[1, 2, 3, 4, 5, 6, 7, 8],
        client: "Millennium Capital",
        market: "HK",
        quantity: 2500,
        notionalValue: 1025000,
        quantityChange: 6000,
        sharesPercent: 2,
        lastDate: "08/06/23"
    },
    {
        stockCode: "0005.HK",
        stockDescription: "HSBC Holdings",
        currency: "HKD",
        score:[1, 2, 3],
        client: "Schroders",
        market: "HK",
        quantity: 3500,
        notionalValue: 143500,
        quantityChange: 500,
        sharesPercent: 1.4,
        lastDate: "09/06/23"
    },
    {
        stockCode: "0005.HK",
        stockDescription: "HSBC Holdings",
        currency: "HKD",
        score:[1, 2, 3, 4],
        client: "Morgan Stanley",
        market: "HK",
        quantity: 14500,
        notionalValue: 5945000,
        quantityChange: 1200,
        sharesPercent: 1.01,
        lastDate: "09/06/23"
    }
];
export const tradeHistory = [
    {
        stockCode: '0001.HK',
        stockDescription: 'CK Hutchison Holdings',
        currency: 'HKD',
        side: 'Buy',
        client: 'Goldman Sachs',
        Market: 'HK',
        date: '08/06/23',
        averagePrice: 50.25,
        desk: 'LowTouch HK',
        trader: 'John Doe',
        originalQuantity: 30000,
        originalNotionalValue: 1500000,
        currentQuantity: 25000,
        currentNotionalValue: 1250000,
    },
    {
        stockCode: '0001.HK',
        stockDescription: 'CK Hutchison Holdings',
        currency: 'HKD',
        side: 'Buy',
        client: 'Goldman Sachs',
        Market: 'HK',
        date: '08/06/23',
        averagePrice: 48.75,
        desk: 'HighTouch SG',
        trader: 'Jane Smith',
        originalQuantity: 20000,
        originalNotionalValue: 960000,
        currentQuantity: 18000,
        currentNotionalValue: 864000,
    },
    {
        stockCode: '0700.HK',
        stockDescription: 'Tencent Holdings',
        currency: 'HKD',
        side: 'Buy',
        client: 'Goldman Sachs',
        Market: 'HK',
        date: '08/06/23',
        averagePrice: 535.50,
        desk: 'LowTouch HK',
        trader: 'Emily Brown',
        originalQuantity: 1200,
        originalNotionalValue: 63600,
        currentQuantity: 1000,
        currentNotionalValue: 53550,
    },
    {
        stockCode: '0001.HK',
        stockDescription: 'CK Hutchison Holdings',
        currency: 'HKD',
        side: 'Sell',
        client: 'Goldman Sachs',
        Market: 'HK',
        date: '08/06/23',
        averagePrice: 56.50,
        desk: 'Equity Derivatives HK',
        trader: 'David Chen',
        originalQuantity: 80000,
        originalNotionalValue: 4480000,
        currentQuantity: 78000,
        currentNotionalValue: 4368000,
    },
    {
        stockCode: '0001.HK',
        stockDescription: 'CK Hutchison Holdings',
        currency: 'HKD',
        side: 'Sell',
        client: 'Goldman Sachs',
        Market: 'HK',
        date: '09/06/23',
        averagePrice: 58.20,
        desk: 'HighTouch HK',
        trader: 'Sophia Liu',
        originalQuantity: 7000,
        originalNotionalValue: 406000,
        currentQuantity: 6500,
        currentNotionalValue: 377750,
    },
    {
        stockCode: '0001.HK',
        stockDescription: 'CK Hutchison Holdings',
        currency: 'HKD',
        side: 'Sell',
        client: 'Goldman Sachs',
        Market: 'HK',
        date: '05/06/23',
        averagePrice: 53.80,
        desk: 'LowTouch AU',
        trader: 'John Smith',
        originalQuantity: 15000,
        originalNotionalValue: 807000,
        currentQuantity: 14500,
        currentNotionalValue: 780500,
    },
    {
        stockCode: '0700.HK',
        stockDescription: 'Tencent Holdings',
        currency: 'HKD',
        side: 'Sell',
        client: 'Goldman Sachs',
        Market: 'HK',
        date: '08/06/23',
        averagePrice: 556.80,
        desk: 'Equity Derivatives SG',
        trader: 'Michael Johnson',
        originalQuantity: 5000,
        originalNotionalValue: 276250,
        currentQuantity: 4800,
        currentNotionalValue: 265200,
    },
    {
        stockCode: '0005.HK',
        stockDescription: 'HSBC Holdings',
        currency: 'HKD',
        side: 'Buy',
        Market: 'HK',
        client: 'Deutsche Bank',
        date: '08/06/23',
        averagePrice: 50.25,
        desk: 'LowTouch HK',
        trader: 'John Doe',
        originalQuantity: 30000,
        originalNotionalValue: 1500000,
        currentQuantity: 25000,
        currentNotionalValue: 1250000,
    },
    {
        stockCode: '0005.HK',
        stockDescription: 'HSBC Holdings',
        currency: 'HKD',
        side: 'Buy',
        Market: 'HK',
        client: 'Morgan Stanley',
        date: '09/06/23',
        averagePrice: 48.75,
        desk: 'HighTouch SG',
        trader: 'Jane Smith',
        originalQuantity: 20000,
        originalNotionalValue: 960000,
        currentQuantity: 18000,
        currentNotionalValue: 864000,
    },
    {
        stockCode: '0005.HK',
        stockDescription: 'HSBC Holdings',
        currency: 'HKD',
        side: 'Sell',
        Market: 'HK',
        client: 'Millennium Capital',
        date: '08/06/23',
        averagePrice: 56.50,
        desk: 'Equity Derivatives HK',
        trader: 'David Chen',
        originalQuantity: 80000,
        originalNotionalValue: 4480000,
        currentQuantity: 78000,
        currentNotionalValue: 4368000,
    }
];
export const tasks = [
    {
        id: 1,
        type: "Potential Cross",
        stockCode: "0001.HK",
        stockDescription: "CK Hutchison Holdings",
        status: "pending",
        timestamp: "2021-06-23T10:00:00.000Z",
        isLive: true,
        market: "HK",
        metadata: "Contact HK low-touch",
        ranking: 8,
        desk: "Low-touch HK",
        quantity: 10000,
        trader: "Horatio",
        side: "Buy"
    },
    {
        id: 2,
        type: "Desk Cross",
        stockCode: "0005.HK",
        stockDescription: "HSBC Holdings",
        status: "pending",
        timestamp: "2021-06-23T11:00:00.000Z",
        isLive: true,
        market: "HK",
        metadata: "Contact Lee McQueen",
        ranking: 9,
        desk: "Block desk HK",
        client: "JP Morgan Chase",
        quantity: 45000,
        trader: "Harper",
        side: "Sell",
        orderId: 1125111
    },
    {
        id: 3,
        type: "Blast",
        stockCode: "0003.HK",
        stockDescription: "Hong Kong and China Gas",
        status: "completed",
        timestamp: "2021-06-23T11:30:00.000Z",
        isLive: true,
        market: "HK",
        metadata: "Contact JP Morgan Block desk",
        ranking: 5
    },
    {
        id: 4,
        type: "Blast",
        stockCode: "0005.HK",
        stockDescription: "Hong Kong and China Gas",
        status: "pending",
        timestamp: "2021-06-23T11:35:00.000Z",
        isLive: false,
        market: "HK",
        metadata: "Goldman Facil desk",
        ranking: 3
    },
    {
        id: 5,
        type: "Order",
        stockCode: "8602.T",
        stockDescription: "Daiwa Securities",
        status: "pending",
        timestamp: "2021-06-23T11:36:00.000Z",
        isLive: true,
        market: "TK",
        metadata: "Deutsche aggressive seller",
        ranking: 6,
        desk: "Facil desk Tokyo",
        client: "Deutsche Bank",
        quantity: 900000,
        trader: "Harry",
        side: "Sell",
        orderId: 1225117
    },
    {
        id: 6,
        type: "Order",
        stockCode: "8604.T",
        stockDescription: "Nomura Holdings",
        status: "pending",
        timestamp: "2021-06-23T11:36:00.000Z",
        isLive: true,
        market: "TK",
        metadata: "Morgan Stanley passive buyer",
        ranking: 2,
        client: "Morgan Stanley",
        quantity: 22400,
        side: "Buy",
        orderId: 1235668
    },
    {
        id: 6,
        type: "Alert",
        stockCode: "8604.T",
        stockDescription: "Nomura Holdings",
        status: "pending",
        timestamp: "2021-06-23T11:36:00.000Z",
        isLive: true,
        market: "TK",
        metadata: "VWAP algo paused",
        ranking: 1,
        client: "JP Morgan Chase",
        quantity: 45000,
        side: "Sell",
        orderId: 1234567

    },
    {
        id: 7,
        type: "IOI Cross",
        stockCode: "2800.HK",
        stockDescription: "Tracker Fund of Hong Kong",
        status: "pending",
        timestamp: "2021-06-23T11:36:20.000Z",
        isLive: true,
        market: "HK",
        metadata: "Large IOI from Goldman",
        ranking: 6,
        client: "Goldman Sachs",
        quantity: 1900000,
        side: "Buy",
        trader: "Sophia Liu",
    }
];

